# Setup
title: Shuhao Du
description: A 21-year old boy
url: https://shuhaodu2003.github.io/
avatar: /avatar.jpg
paginate: 3
permalink: /:title.html
cover_image: /bg.jpg

# Use Jekyll Functions
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Exclude Unrelated Files
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag

google-site-verification: haven't verified
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Author
author:
  name: Shuhao Du
  url: https://shuhaodu2003.github.io/
  email: hdfydsh@163.com
